### ISSUE TITLE
Bump version to 0.4.2

### ISSUE THREAD

**Issue by eaon** [vhdirk/notmuch-rs#17]
Heya,

Since I assume the API breaking changes (due to the new lifetime info you gathered) will happen in a 0.5 release, I wondered if you'd consider releasing 0.4.2. It'd allow me to publish a new version of [notcoal](https://ghom.niij.org/eaon/notcoal) :smiley: 

Thanks

**Comment by vhdirk** [comment]
Ah yes. Sorry. I'll get to that asap.

**Comment by vhdirk** [comment]
é voila. Uploaded to crates.io.

**Comment by eaon** [comment]
[Thanks](https://crates.io/crates/notcoal/0.2.5)!
