### ISSUE TITLE
Non-2018 edition compatibility

### ISSUE THREAD

**Issue by rhn** [vhdirk/notmuch-rs#19]
Recently, the library became 2018-edition only, without the possibility to use it when the compiler is older. 

Fedora breaks its regular update cycle for Rust, updating it earlier than 95% other packages, and is still currently with rustc 1.30.1, which complains that it doesn't do 2018.

According to the [Rust survey](https://blog.rust-lang.org/2018/11/27/Rust-survey-2018.html), Linux distro packages account for 17% users, plus some more for Homebrew. They will be broken, and some will stay broken for the following months-years, depending on the release cycle.

I don't see a reason to break those users (myself included) unless notmuch-rs cannot work at all without some feature of the 2018 edition. Would a revert of b5b0f7e97abe0dbd5b54a1fc69e764a124c271b2 be accepted?

**Comment by vhdirk** [comment]
Hmm, I didn't think about that. We can certainly revert this, yes. I was more concerned with compatibility with non-2018 crates, that I forgot about older compilers.

**Comment by rhn** [comment]
Thank you!
