### ISSUE TITLE
index_file missing on Database?

### ISSUE THREAD

**Issue by gauteh** [vhdirk/notmuch-rs#25]
I may be completely missing something, but is `Database::index_file` missing?

**Comment by vhdirk** [comment]
Yup, it is. I guess it's far from the only method still missing. I started off from the absolute minimum. I'll add it ASAP.

**Comment by vhdirk** [comment]
@gauteh I've implemented index_file in master, but haven't had the time to test it. Care to help me out?

**Comment by gauteh** [comment]
Yup, thanks, I should have the chance somewhen this weekend hopefully.

**Comment by vhdirk** [comment]
@gauteh I'm in the process of porting some of the original notmuch unit tests to notmuch-rs. Not sure when I'll be able to make much progress in that area. I'll close this issue once the ffi binding has been validated

**Comment by gauteh** [comment]
Ok. Sorry, I have not been able to test yet. But it definetely looks like it should work...

**Comment by vhdirk** [comment]
Since there are now unit tests I can now safely say that ```index_file``` is working

**Comment by gauteh** [comment]
Thanks!
