### ISSUE TITLE
How to get a thread from a single message?

### ISSUE THREAD

**Issue by matthiasbeyer** [vhdirk/notmuch-rs#26]
Hi,

as far as I can see, the API does not (yet) offer a way to get the full thread for a single message?

Something like `database.get_thread(message.thread_id())` or similar.

From what I see, I have to create a query: `database.create_query(format!("thread:{}", message.thread_id()))?.search_threads()?...` for this, am I right?

Would be nice to have a convenience function for that usecase.

**Comment by vhdirk** [comment]
Does notmuch itsef provide functions like that? I'm not against adding convenience functions like this but I would like to keep them separate. The core of this crate should mirror notmuch-c as close as possbile.

**Comment by matthiasbeyer** [comment]
Yeah, sorry that I did not close this issue when I solved my problem.

So what you do is, you get the message object, get the thread id from it and then create a query `thread:<thread id>` and pass that to notmuch.

At least that did it for me.
