### ISSUE TITLE
Examine lifetimes

### ISSUE THREAD

**Issue by vhdirk** [vhdirk/notmuch-rs#3]
The lifetimes of the pointer handles are not all correctly defined. For instance, ```Thread``` objects as returned by the ```Threads``` iterator are actually bound to the iterator. If the iterator gets destroyed, all thread pointers are destroyed as well.
Same goes for ```Message```. There may be more such cases. Notmuch's documentation isn't always clear.

For ```Tags``` it's even less correct as it is now. The lifetime of ```Tags``` should be bound to the owner, which is not always purely ```Database```. It is for ```db.all_tags()```, but for  ```Thread.tags()```, the lifetime chain would become: ``` Database > Query > Threads > Thread > Tags```.

**Comment by vhdirk** [comment]
@rhn You mentioned you haven't encountered any issues with lifetimes. I've been looking into notquick, and it seems that the ```Threads``` iterator is immediately iterated, after which the data from the threads is cloned. It's all single-threaded as well. Is that correct?

**Comment by rhn** [comment]
Yes, that seems to be right. I didn't strain the library much yet.

**Comment by vhdirk** [comment]
@rhn @eaon 
I've fixed several errors regarding lifetimes in the 'lifetimes' branch. Now, notmuch-rs will correctly respect lifetimes according to libnotmuch.
As for storing items along with their owner, the standard approaches are ```rental``` or ```owningref```. I just came accross https://docs.rs/supercow/0.1.0/supercow/, which seems to do exactly what I need.
Unless you see any serious disadvantages, I'll probably go with supercow.

**Comment by rhn** [comment]
I can't say much right now, as other stuff took over again (curse those responsibilities), so I'm unlikely to take a closer look before a week passes.

**Comment by eaon** [comment]
Tried the lifetimes branch, works for me (with a couple of minimal changes). As far as storing items goes, I haven't found need for that yet, so please, go ahead and implement it the way you like it :+1: Thanks for sharing your work!

**Comment by vhdirk** [comment]
@eaon did you mean you needed to make any changes to notmuch-rs? If so, I'd like to know what they are.

**Comment by eaon** [comment]
Oh, sorry, this was a comment about changes to my own code because of the MessageOwner trait related bits (none of which is public at the moment).

I haven't changed anything related to lifetimes, the only thing I touched recently in notmuch-rs was [adding add_tag/remove_tag/remove_all_tags in my fork](https://github.com/eaon/notmuch-rs) (on top of your lifetime branch)

**Comment by vhdirk** [comment]
I'm nearly ready reworking/improving lifetime management with SuperCow. Once that makes it into master, I'll happily accept any PRs you can make for those additions.

**Comment by vhdirk** [comment]
Reopening this since the documentation of notmuch is terribly confusing.
The iterators have in fact no ownership over the items they iterate over. Additionally, you can't just 'destroy' items, since they are not one-off items...

**Comment by vhdirk** [comment]
Fixed in 0.5.0

**Comment by rhn** [comment]
If I haven't said this before, I love the change and it's been a breeze to work with notmuch-rs now.

**Comment by vhdirk** [comment]
@rhn Thanks! Currently it still lacks ```Drop``` for ```Message```, and I'm not sure how to add that since it may only be implemented for the case where ```Owner``` is ```Query```. However, rust nightly seems to be adding RTTI, so it may be possible at some point. I'm not sure what the impact is, but the notmuch documentation seems to suggest that it's not typically needed to call ```notmuch_message_destroy``` anyway.
