### ISSUE TITLE
notmuch_database_open_with_config is required for split db/mail path support

### ISSUE THREAD

**Issue by OJFord** [vhdirk/notmuch-rs#34]
After a bit of digging into an issue I _nearly_ reported, I determined that the notmuch API doesn't support distinct `db_path` and `mail_root`s (new in v0.32). After a chat on [irc://irc.libera.chat/#notmuch](//web.libera.chat) it seems a) yes it doesn't; b) there is a new opener function `notmuch_database_open_with_config` that does; c) it cannot be compatibly fixed.

Since notmuch-rs does not use that new API, it's currently not possible to do anything with it that attempts to open and parse the file (look at non-indexed headers, etc.).

The fix I would suggest (and intend to get around to a PR for soon) is to add an `Option<Path>` arg to `Database::open` for the config, with the current behaviour when `None`, and using the new C fn if `Some`.

**Comment by elizagamedev** [comment]
This should be fixed by #39

**Comment by OJFord** [comment]
Thanks @elizagamedev!
