### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by elizagamedev** [vhdirk/notmuch-rs#42]
Hello,

I'd like to request a new minor release of notmuch-rs with the `open_with_config` API and the `DUPLICATE_MESSAGE_ID` fix. My project [mujmap](https://github.com/elizagamedev/mujmap) depends on this for a release on crates.io.

**Comment by vhdirk** [comment]
just published v0.7.2. Sorry I didn't do this earlier. Life's pretty hectic these days.

**Comment by elizagamedev** [comment]
Understandable! Thank you so much 🙂
