### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by vhdirk** [vhdirk/notmuch-rs#7]
There's currently only one test, and it doesn't necessarily test anything since the existence of a maildir is optional for the test to pass.

**Comment by rhn** [comment]
While it's true that the supplied test doesn't test runtime compliance, it provides a guard rail against the insanity of the API. Another kind of a test might want to check against C library enforced invariants (e.g. should not compile if the drop order is broken). One of them is mentioned in https://github.com/vhdirk/notmuch-rs/issues/24

**Comment by vhdirk** [comment]
Since commit 084675f, unit tests are now included. They are closely modeled after the original notdb python-cffi bindings.
